# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./test.h

#Source files
SOURCES += ./main.cpp \
    ./test.cpp

#Forms
FORMS += ./test.ui

#Resource file(s)
RESOURCES += ./style.qrc \
    ./test.qrc
